/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Approval: typeof import('./components/Approval.vue')['default']
    CodeInput: typeof import('./components/CodeInput.vue')['default']
    ColorPicker: typeof import('./components/ColorPicker.tsx')['default']
    Error: typeof import('./components/Error.tsx')['default']
    GoogleCode: typeof import('./components/Dialog/GoogleCode.vue')['default']
    Header: typeof import('./components/Header.tsx')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Index: typeof import('./components/TableSearchWrap/Index.tsx')['default']
    ListApproval: typeof import('./components/ListApproval.vue')['default']
    NotRolePurview: typeof import('./components/NotRolePurview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavigationBar: typeof import('./components/SideNavigationBar.tsx')['default']
    TagsView: typeof import('./components/TagsView.vue')['default']
  }
}
